#!/bin/bash

set -ev

# Source reads
READS=$2

# Destination directory
DIR=$3
LOG=$DIR/log.txt
ASSEMBLY=$DIR/contigs.fa

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

TMP_DIR=`mktemp -d`
cd $TMP_DIR

eval ${CMD}

cp genome-contigs.fa $ASSEMBLY

rm reads.fq read_1.fq read_2.fq
