#!/bin/bash

set -o errexit
set -o nounset

# Source reads
READS=$2

# Destination directory
DIR=$3
ASSEMBLY=$DIR/contigs.fa
LOG=$DIR/log.txt

exec > >(tee ${LOG})
exec 2>&1
set -o xtrace

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

TMP_DIR=`mktemp -d`
cd $TMP_DIR

eval ${CMD}

cp genome-contigs.fa $ASSEMBLY
